# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

version: '2.0'

services:
  notebook:
    build: .
    image: lujianmei/docker-datascience-notebook
    container_name: ${NAME}
    volumes:
     - "workspace:/workspace/data-scientist-notes"
    ports:
     - "${PORT}:8888"
    depends_on:
      - postgres

  postgres:
    image: postgres


volumes:
  workspace:
    external:
      name: ${WORK_VOLUME}
